apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rslim087a/argocd-kubernetes-gitops-tutorial.git
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true